dist: trusty
sudo: required
language: python
python:
  - "3.4"
addons:
  apt:
    packages:
    - automake
    - libtool
    - pkg-config
    - autoconf
    - libssl-dev
    - check
    - libjansson-dev
    - git
    - apache2
    - apache2-dev
before_install:
  - git clone https://github.com/benmcollins/libjwt
  - cd libjwt
  - git checkout tags/v1.12.0 -q
  - autoreconf -i
  - ./configure 
  - make 
  - sudo make install 
  - sudo ldconfig
  - cd ..
install:
  - autoreconf -ivf
  - ./configure
  - make
  - sudo make install
before_script:
  - pip install pyjwt requests cryptography
  - chmod ugo+x tests/debian_tests.sh
  - cd tests
script: ./debian_tests.sh

